name: HolaCraft
main: tk.holacraft.Main
version: 0.2.1
author: playajames

commands:
  hola:
    description: HolaCraft main control command.
  spawn:
    desctiption: Teleports player to spawn location.
  warp:
    desctiption: Teleports player to specified warp location.
  money:
    description: Allows players to control their money.
  home:
    description: Allows players to control their homes.
  mute:
    description: Toggle mute players.
  warn:
    description: Warns players.